kind: pipeline
type: docker
name: push to github

steps:
- name: push to git
  image: appleboy/drone-git-push
  settings:
    branch: develop
    remote: ssh://git@github.com:22/myles3850/shelftracker-proj.git
    force: false
    commit: true

trigger:
  event:
  - push

  

---

kind: pipeline
type: docker
name: shelftracker

steps:
- name: build
  image: node:current-alpine
  commands:
  - npm i

- name: lint check
  image: node:current-alpine
  commands:
  - npm run lint

- name: run tests
  image: node:current-alpine
  commands:
  - npm run test


trigger:
  event:
  - push
