version: "3.8"

services:
  api:
    build:
      context: .
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=example
      - DB_DATABASE=shelftracker-prod
    restart: always
    ports:
      - 3000:3000
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=16M
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: shelftracker-prod

    ports:
      - 3306:3306
